$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

$env:PYTHONUTF8 = "1"
$env:PYTHONIOENCODING = "utf-8"
$env:UV_CACHE_DIR = Join-Path $Root "data\\.uv-cache"
try {
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
} catch {
}

$LogDir = Join-Path $Root "data\logs"
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
New-Item -ItemType Directory -Force -Path $env:UV_CACHE_DIR | Out-Null

$RunStamp = Get-Date -Format "yyyy-MM-dd-HHmmss"
$LogPath = Join-Path $LogDir "horizon-$RunStamp.log"

function Send-ChatMessage {
    param([string]$Message)

    $cc = Get-Command cc-connect -ErrorAction SilentlyContinue
    $ccSocket = Join-Path $env:USERPROFILE ".cc-connect\run\api.sock"
    if ($cc -and (Test-Path $ccSocket)) {
        try {
            $Message | & cc-connect send --stdin 2>$null
            if ($LASTEXITCODE -ne 0) {
                Write-Host $Message
            }
        } catch {
            Write-Host $Message
        }
    } else {
        Write-Host $Message
    }
}

if (-not (Test-Path ".env")) {
    Send-ChatMessage "Horizon daily AI news did not run: missing .env at $Root\.env. Add DEEPSEEK_API_KEY first."
    exit 2
}

$envContent = Get-Content ".env" -ErrorAction Stop
$deepseekLine = $envContent |
    Where-Object { $_ -match "^\s*DEEPSEEK_API_KEY\s*=" -and $_ -notmatch "^\s*#" } |
    Select-Object -First 1

$deepseekKey = $env:DEEPSEEK_API_KEY
if ($deepseekLine) {
    $deepseekFileValue = ($deepseekLine -replace "^\s*DEEPSEEK_API_KEY\s*=", "").Trim().Trim('"').Trim("'")
    if (-not [string]::IsNullOrWhiteSpace($deepseekFileValue)) {
        $deepseekKey = $deepseekFileValue
    }
}

if ([string]::IsNullOrWhiteSpace($deepseekKey) -or $deepseekKey -match "your|xxx|placeholder") {
    Send-ChatMessage "Horizon daily AI news is configured, but DEEPSEEK_API_KEY is empty. Edit $Root\.env and add your DeepSeek API key, then run again."
    exit 2
}

try {
    "[$(Get-Date -Format o)] Starting Horizon daily AI news run" | Tee-Object -FilePath $LogPath

    $Command = "chcp 65001 >nul && python -m uv run horizon --hours 24 >> ""$LogPath"" 2>&1"
    & cmd.exe /d /c $Command
    $ExitCode = $LASTEXITCODE

    if ($ExitCode -ne 0) {
        throw "horizon exited with code $ExitCode"
    }
} catch {
    Send-ChatMessage "Horizon daily AI news failed: $($_.Exception.Message)`nLog: $LogPath"
    exit 1
}

$Summary = Get-ChildItem -Path (Join-Path $Root "data\summaries") -Filter "horizon-*-zh.md" -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $Summary) {
    Send-ChatMessage "Horizon finished, but no Chinese summary file was found. Log: $LogPath"
    exit 1
}

$SummaryText = Get-Content -Raw -Encoding UTF8 $Summary.FullName
$PreviewLines = ($SummaryText -split "`r?`n" | Select-Object -First 40) -join "`n"
$Message = @"
Daily AI News generated by Horizon
Summary file: $($Summary.FullName)

$PreviewLines

(truncated preview; open the file for full content)
"@

Send-ChatMessage $Message
